[build]
builder = "railpack"

[php]
version = "8.2"
extensions = [
  "zip",
  "curl",
  "openssl",
  "pdo",
  "pdo_mysql",
  "mbstring",
  "fileinfo"
]

[deploy]
start = "php artisan serve --host=0.0.0.0 --port=${PORT}"
